name: growled
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cloud_firestore:
  flutter:
    sdk: flutter
  flutter_screenutil: ^0.6.0
  rflutter_alert: ^1.0.3
  firebase_auth:
  firebase_database: ^3.0.7
  firebase_core: any
    
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - images/header-img.png
   - images/image_02.png
   - images/logo.png
   - images/image_01.png
   - images/plant.png
   - images/logo-1.png

  fonts:
    

    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf  
